services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kk-ops-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_NAME=cmdb
      - JWT_SECRET=kk-ops-secure-jwt-token-2025
    networks:
      - kk-ops-network
    volumes:
      - ./migrations:/app/migrations

  db:
    image: postgres:15-alpine
    container_name: kk-ops-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=cmdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kk-ops-network

networks:
  kk-ops-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local